name: elegant_video_full
description: 视频站完整 Demo：支持登录、播放、路由跳转
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  flutter_vlc_player: ^7.2.0

flutter:
  uses-material-design: true
