name: elegant_video
description: A decentralized elegant video streaming app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  better_player:
    git:
      url: https://github.com/furkanaskin/betterplayer_fork.git
      ref: main
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
