name: elegant_video_web_ready
description: 修复视频播放 + 页面跳转 + Web 可部署支持
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  video_player: ^2.7.0

flutter:
  uses-material-design: true
